name: C++ CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Check out your repository code

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make libgtest-dev  # Install g++, make, and Google Test

      - name: Compile Google Test
        run: |
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/lib  # Copy libgtest.a and libgtest_main.a to /usr/lib

      - name: Compile and Run Tests
        run: |
          g++ -isystem /usr/include/gtest -I. -pthread ./calctest.cpp /usr/lib/libgtest.a /usr/lib/libgtest_main.a -o calctest
          ./calctest  # Execute the compiled test executable
